// List of countries with their major crops
export const countryCrops = {
  "Afghanistan": ["Wheat", "Rice", "Corn", "Cotton", "Fruits", "Vegetables"],
  "Albania": ["Wheat", "Corn", "Potatoes", "Vegetables", "Fruits", "Grapes"],
  "Algeria": ["Wheat", "Barley", "Potatoes", "Dates", "Citrus", "Olives"],
  "Angola": ["Cassava", "Corn", "Sweet Potatoes", "Coffee", "Cotton"],
  "Argentina": ["Soybeans", "Corn", "Wheat", "Sunflower", "Grapes"],
  "Australia": ["Wheat", "Barley", "Canola", "Cotton", "Sugarcane"],
  "Bangladesh": ["Rice", "Jute", "Tea", "Wheat", "Vegetables"],
  "Brazil": ["Soybeans", "Corn", "Sugarcane", "Coffee", "Cotton"],
  "Cambodia": ["Rice", "Corn", "Cassava", "Rubber", "Vegetables"],
  "Cameroon": ["Cassava", "Corn", "Plantains", "Cocoa", "Coffee"],
  "Canada": ["Wheat", "Canola", "Barley", "Corn", "Soybeans"],
  "Chad": ["Sorghum", "Millet", "Peanuts", "Cotton", "Rice"],
  "Chile": ["Grapes", "Apples", "Wheat", "Corn", "Potatoes"],
  "China": ["Rice", "Wheat", "Corn", "Soybeans", "Cotton"],
  "Colombia": ["Coffee", "Bananas", "Rice", "Corn", "Sugarcane"],
  "Costa Rica": ["Coffee", "Bananas", "Pineapples", "Sugar", "Rice"],
  "Côte d'Ivoire": ["Cocoa", "Coffee", "Bananas", "Rubber", "Palm Oil"],
  "Cuba": ["Sugarcane", "Tobacco", "Rice", "Citrus", "Coffee"],
  "Democratic Republic of the Congo": ["Cassava", "Corn", "Rice", "Coffee", "Cocoa"],
  "Dominican Republic": ["Sugarcane", "Coffee", "Cocoa", "Tobacco", "Rice"],
  "Ecuador": ["Bananas", "Coffee", "Cocoa", "Rice", "Corn"],
  "Egypt": ["Cotton", "Rice", "Wheat", "Corn", "Sugarcane"],
  "El Salvador": ["Coffee", "Corn", "Sugarcane", "Rice", "Beans"],
  "Ethiopia": ["Coffee", "Teff", "Corn", "Wheat", "Barley"],
  "France": ["Wheat", "Corn", "Barley", "Grapes", "Sunflower"],
  "Germany": ["Wheat", "Barley", "Rapeseed", "Potatoes", "Sugar Beets"],
  "Ghana": ["Cocoa", "Coffee", "Corn", "Cassava", "Yams"],
  "Greece": ["Olives", "Grapes", "Wheat", "Corn", "Cotton"],
  "Guatemala": ["Coffee", "Bananas", "Sugarcane", "Corn", "Beans"],
  "Haiti": ["Coffee", "Mangoes", "Corn", "Rice", "Sugarcane"],
  "Honduras": ["Coffee", "Bananas", "Corn", "Beans", "Sugarcane"],
  "India": ["Rice", "Wheat", "Cotton", "Sugarcane", "Tea"],
  "Indonesia": ["Rice", "Palm Oil", "Rubber", "Coffee", "Cocoa"],
  "Iran": ["Wheat", "Rice", "Corn", "Cotton", "Fruits"],
  "Iraq": ["Wheat", "Barley", "Rice", "Dates", "Vegetables"],
  "Italy": ["Grapes", "Wheat", "Corn", "Olives", "Tomatoes"],
  "Jamaica": ["Sugarcane", "Bananas", "Coffee", "Cocoa", "Citrus"],
  "Japan": ["Rice", "Vegetables", "Fruits", "Wheat", "Soybeans"],
  "Jordan": ["Wheat", "Barley", "Vegetables", "Fruits", "Olives"],
  "Kazakhstan": ["Wheat", "Barley", "Corn", "Sunflower", "Potatoes"],
  "Kenya": ["Tea", "Coffee", "Corn", "Wheat", "Sugarcane"],
  "Korea, North": ["Rice", "Corn", "Potatoes", "Soybeans", "Vegetables"],
  "Korea, South": ["Rice", "Vegetables", "Fruits", "Barley", "Soybeans"],
  "Kuwait": ["Vegetables", "Fruits", "Dates", "Grains"],
  "Laos": ["Rice", "Coffee", "Corn", "Cassava", "Vegetables"],
  "Lebanon": ["Fruits", "Vegetables", "Olives", "Tobacco", "Grapes"],
  "Libya": ["Wheat", "Barley", "Olives", "Dates", "Vegetables"],
  "Madagascar": ["Rice", "Cassava", "Corn", "Sweet Potatoes", "Coffee"],
  "Malawi": ["Tobacco", "Tea", "Sugarcane", "Corn", "Cotton"],
  "Malaysia": ["Palm Oil", "Rubber", "Rice", "Cocoa", "Coffee"],
  "Mali": ["Cotton", "Rice", "Millet", "Corn", "Sorghum"],
  "Mexico": ["Corn", "Wheat", "Sugarcane", "Coffee", "Beans"],
  "Morocco": ["Wheat", "Barley", "Citrus", "Vegetables", "Olives"],
  "Mozambique": ["Cassava", "Corn", "Rice", "Cotton", "Sugarcane"],
  "Myanmar": ["Rice", "Corn", "Sugarcane", "Pulses", "Vegetables"],
  "Nepal": ["Rice", "Corn", "Wheat", "Potatoes", "Sugarcane"],
  "Netherlands": ["Potatoes", "Vegetables", "Flowers", "Grains", "Sugar Beets"],
  "New Zealand": ["Dairy", "Sheep", "Beef", "Wheat", "Barley"],
  "Nicaragua": ["Coffee", "Beans", "Corn", "Rice", "Sugarcane"],
  "Nigeria": ["Cassava", "Yams", "Corn", "Rice", "Sorghum"],
  "Norway": ["Barley", "Oats", "Potatoes", "Vegetables", "Fruits"],
  "Pakistan": ["Wheat", "Rice", "Cotton", "Sugarcane", "Corn"],
  "Panama": ["Bananas", "Coffee", "Sugarcane", "Rice", "Corn"],
  "Papua New Guinea": ["Coffee", "Cocoa", "Copra", "Palm Oil", "Tea"],
  "Paraguay": ["Soybeans", "Corn", "Wheat", "Sugarcane", "Cotton"],
  "Peru": ["Coffee", "Cocoa", "Rice", "Corn", "Potatoes"],
  "Philippines": ["Rice", "Corn", "Coconuts", "Sugarcane", "Bananas"],
  "Poland": ["Wheat", "Rye", "Potatoes", "Sugar Beets", "Rapeseed"],
  "Portugal": ["Grapes", "Olives", "Corn", "Wheat", "Potatoes"],
  "Romania": ["Wheat", "Corn", "Sunflower", "Potatoes", "Rapeseed"],
  "Russia": ["Wheat", "Barley", "Sunflower", "Potatoes", "Sugar Beets"],
  "Rwanda": ["Coffee", "Tea", "Bananas", "Beans", "Sorghum"],
  "Saudi Arabia": ["Wheat", "Barley", "Dates", "Vegetables", "Fruits"],
  "Senegal": ["Peanuts", "Millet", "Rice", "Corn", "Sorghum"],
  "Serbia": ["Wheat", "Corn", "Sunflower", "Sugar Beets", "Rapeseed"],
  "Sierra Leone": ["Rice", "Coffee", "Cocoa", "Palm Oil", "Cassava"],
  "Somalia": ["Bananas", "Corn", "Sorghum", "Sugarcane", "Cassava"],
  "South Africa": ["Corn", "Wheat", "Sugarcane", "Sunflower", "Grapes"],
  "Spain": ["Grapes", "Olives", "Wheat", "Corn", "Citrus"],
  "Sri Lanka": ["Rice", "Tea", "Rubber", "Coconuts", "Spices"],
  "Sudan": ["Sorghum", "Millet", "Wheat", "Cotton", "Sesame"],
  "Sweden": ["Barley", "Wheat", "Oats", "Rapeseed", "Potatoes"],
  "Switzerland": ["Wheat", "Barley", "Potatoes", "Rapeseed", "Sugar Beets"],
  "Syria": ["Wheat", "Barley", "Cotton", "Olives", "Fruits"],
  "Taiwan": ["Rice", "Vegetables", "Fruits", "Tea", "Sugarcane"],
  "Tanzania": ["Coffee", "Tea", "Cotton", "Cashews", "Tobacco"],
  "Thailand": ["Rice", "Rubber", "Corn", "Sugarcane", "Cassava"],
  "Tunisia": ["Olives", "Wheat", "Barley", "Dates", "Citrus"],
  "Turkey": ["Wheat", "Barley", "Cotton", "Tobacco", "Fruits"],
  "Uganda": ["Coffee", "Tea", "Cotton", "Tobacco", "Cassava"],
  "Ukraine": ["Wheat", "Corn", "Sunflower", "Barley", "Sugar Beets"],
  "United Kingdom": ["Wheat", "Barley", "Rapeseed", "Potatoes", "Sugar Beets"],
  "United States": ["Corn", "Soybeans", "Wheat", "Cotton", "Hay"],
  "Uruguay": ["Soybeans", "Wheat", "Rice", "Barley", "Corn"],
  "Venezuela": ["Corn", "Rice", "Coffee", "Cocoa", "Sugarcane"],
  "Vietnam": ["Rice", "Coffee", "Rubber", "Tea", "Pepper"],
  "Yemen": ["Coffee", "Cotton", "Fruits", "Vegetables", "Grains"],
  "Zambia": ["Corn", "Cotton", "Soybeans", "Tobacco", "Sugarcane"],
  "Zimbabwe": ["Tobacco", "Corn", "Cotton", "Wheat", "Soybeans"]
};

// Get list of all countries
export const countries = Object.keys(countryCrops).sort();

// Get crops for a specific country
export const getCropsForCountry = (country) => {
  return countryCrops[country] || [];
}; 